config/routes.rb
Rails.application.routes.draw do
  get 'welcome_index/index'

  resources :accounts
  resources :users
  
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  
  get '/user/:username' => 'users#show'
  get '/accessdenied' => 'welcome_index#access_denied'
  
  get '/user/:username/edit' => 'users#edit'
  post '/user/:username/edit' => 'users#update'
  
  get '/accounts/:id/transactions/new' => 'transactions#new'
  post '/accounts/:id/transactions/new' => 'transactions#create'
  
  get '/accounts/:id/transactions/:transaction_id' => 'transactions#show'
  get '/accounts/:id/transactions' => 'transactions#index'
  
  get 'accounts/transactions/transfer' => 'transactions#new_transfer'
  post 'accounts/transactions/transfer' => 'transactions#transfer'
  
  get '/productivity' => 'time_waster#index'
  
  get '/snake' => 'time_waster#snake'
  get '/snake_score' => 'time_waster#snake_score'
  post '/time_waster' => 'time_waster#store_score'
  
  get '/pong' => 'time_waster#launch_pong', as: '/pong/play'
  get '/pong/servers' => 'time_waster#pong_server_browser'
  get '/pong/game/:id' => 'time_waster#pong'
  get '/pong/game/:id/begin' => 'time_waster#begin_pong_game'
  get '/pong/update/get/:id' => 'time_waster#pong_response'
  get '/pong/status/:id' => 'time_waster#pong_status'
  post '/pong/update/:id' => 'time_waster#pong_update_pos'
  
  root 'welcome_index#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
	has_many :accounts, :dependent => :destroy
	has_many :game_scores, :dependent => :destroy

	STATES = ['AL', 'AK', 'AZ', 'AR', 'CA', 
	'CO', 'CT', 'DE', 'DC', 'FL', 'GA', 'HI', 
	'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 
	'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 
	'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 
	'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 
	'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 
	'WA', 'WV', 'WI', 'WY', 'Other' ]
	
	has_secure_password
	validates_presence_of :password, :on => :create
  
	validates :username, presence: true, length: { minimum: 5}, uniqueness: true
	validates :email, presence: true, uniqueness: true
	validates :address, presence: true
	validates :state, presence: true, length: {maximum: 2}
	validates :zip_code, presence: true, length: {minimum: 5, maximum: 5}
	validates :city, presence: true
	
	validate :password_complexity

	
	private

	def password_complexity
		return if password.nil?

		if password.size < 8
			errors.add :password, "Must be at least 8 characters long."
			return
		end
		
		passed = false
		
		if password.match(/[A-Z]/) && password.match(/[a-z]/) && password.match(/\d/)
			passed = true
		end
		
		if !passed
			errors.add(:password, " does not meet security requirements.")
		end
		
		return passed
	end
	
	def replace_password
		if self.authenticate(self.current_password)			
			if self.new_password != nil
				self.password = self.new_password
			end				
		else	
			errors.add(:current_password, " is incorrect.")
		end
	end
	
	def try_login(password_attempt)
		if self.authenticate(password_attempt)
			return true
		else
			return false
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	# Pages for reading data
	
	def index
		unless current_user && current_user.username == "kingcrusader13"
			redirect_to root_url
		end
		@user = User.all
	end
	
	def show
		if params[:username]
			@user = User.find_by_username(params[:username])
			
			unless current_user
				return redirect_to '/login'
			end
				
			unless @user != nil && current_user != nil && current_user.username == @user.username
				redirect_to '/accessdenied'
			end
		end
	end
	
	# Forms for Put and Post
	
	def new
		@user = User.new
	end

	def edit
		@user = User.find_by_username(params[:username])
		
		unless @user == current_user
			redirect_to '/accessdenied'
		end
	end
	
	# Put, Post, and Destroy methods
	
	def create
		params[:user][:username].downcase!
	
		@user = User.new(user_params)
		
		if @user.save
			redirect_to '/login'
		else
			render 'new'
		end
	end
	
	def update
		@user = User.find_by_username(params[:username])
		
		if @user.authenticate(params[:current_password])
			
			params[:state] = params[:state][:state]
		
			if @user.update_attributes(update_user_params)
				if params[:new_password] != nil && params[:new_password] != ""
					if params[:new_password] == params[:password_confirmation]
						@user.password = params[:new_password]
						@user.save
					else
						@user.errors.add(:new_password, " did not match confirmation!")
						render 'edit'
					end
				end
				redirect_to '/user/' + @user.username
			else
				render 'edit'
			end
		else
			render 'edit'
		end
	end
	
	def destroy
		@user = User.find(params[:id])
		
		if current_user && current_user == @user
			@user.destroy
		end
		
		redirect_to '/logout'
	end
	
	private

	# Params used for user creation
	def user_params
		params.require(:user).permit(:username, :password, :password_confirmation, :email, :city, :state, :zip_code, :address)
	end
	
	# Params used for updating users
	def update_user_params
		params.permit(:email, :city, :state, :zip_code, :address)
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>Edit your info</h1>
<div>
<%= form_tag '/user/' + @user.username.to_s + '/edit' do %>
	
	<% if @user.errors.any? %>
		<div class="error_messages">
			<table>
				<tr>
					<th>Form is invalid</th>
				</tr>
				<% for msg in @user.errors.full_messages %>
					<tr><td><%= msg %></td></tr>
				<% end %>
			</table>
		</div>
	<% end %>
	<div>
		<%= label_tag :email, "Email Address" %>
		<br>
		<%= email_field_tag :email, @user.email %>
	</div>
		<div>
		<%= label_tag :address, "Address" %>
		<br>
		<%= text_field_tag :address, @user.address %>
	</div>	
		<div>
		<%= label_tag :city, "City" %>
		<br>
		<%= text_field_tag :city, @user.city %>
	</div>	
		<div>
		<%= label_tag :state, "State" %>
		<br>
		<%= collection_select :state, :state, User::STATES, :to_s, :to_s, :selected => @user.state %>
	</div>	
		<div>
		<%= label_tag :zip_code, "Zip" %>
		<br>
		<%= text_field_tag :zip_code, @user.zip_code %>
	</div>	
	<div>
		<%= label_tag :current_password, 'Current password' %>
		<br>
		<%= password_field_tag :current_password %>
	</div>
	<div>
		<%= label_tag :new_password, "New Password" %>
		<p style="color: gray; font-size: 13px;">Please use a mix of numbers, uppercase letters, and lowercase letters</p>
		<%= password_field_tag :new_password %>
	</div>	
	<div>
		<%= label_tag :password_confirmation, 'Confirm Password' %>
		<br>
		<%= password_field_tag :password_confirmation %>
	</div>
	<div><%= submit_tag "Update Account" %></div>
<% end %>

<%= link_to 'Back', '/user/' + @user.username %>
<br>
</div>

app/views/users/index.html.erb
<h1>Welcome to the User Management Page</h1>

<div>
<% unless current_user %>
	<%= link_to 'Sign Up', new_user_path %>
<% end %>
<% if User.exists? %>
	<table>
		<tr>
			<th>Username</th>
			<th>Email Address</th>
			<th colspan="2">Actions</th>
		</tr>
		<% User.find_each do |user|%>
			<tr>
				<td><%= user.username %></td>
				<td><%= user.email %></td>
				<td><%= link_to 'Update User Info', '/user/' + user.username + '/edit' %></td>
				<td><%= link_to 'Delete User', user_path(user), method: :delete, data: { confirm: 'Delete user?' } %></td>
			</tr>
		<% end %>
	</table>
<% else %>
	<p>
		There are currently no registered users.
	</p>
<% end %>
</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<div>
<%= form_for @user do |form| %>
	<% if @user.errors.any? %>
		<div class="error_messages">
			Form is invalid
			<p style="color: red;">
				<% for msg in @user.errors.full_messages %>
					<br><%= msg %>
				<% end %>
			</p>
		</div>
	<% end %>
	<div>
		<%= form.label :username, "Username" %>
		<br>
		<%= form.text_field :username %>
	</div>
	<div>
		<%= form.label :email, "Email Address" %><br>
		<%= form.email_field :email %>
	</div>
	<div>
		<%= form.label :password, "Password" %>
		<p style="color: gray; font-size: 13px;">Please use a mix of numbers, uppercase letters, and lowercase letters</p>
		<%= form.password_field :password %>
	</div>
	<div>
		<%= form.label :password_confirmation, "Password Confirmation" %>
		<br>
		<%= form.password_field :password_confirmation %>
	</div>
	<div>
		<%= form.label :address, "Address" %><br>
		<%= form.text_field :address %>
	</div>
	<div>
		<%= form.label :city, "City" %><br>
		<%= form.text_field :city %>
	</div>
	<div>
		<%= form.label :state, "State" %><br>
		<%= form.collection_select :state, User::STATES, :to_s, :to_s %>
	</div>
	<div>
		<%= form.label :zip_code, "Zip" %><br>
		<%= form.text_field :zip_code %>
	</div>
	<div><%= form.submit %></div>

	<%= link_to 'Back', users_path %>
<% end %>
</div>

app/views/users/show.html.erb
<h1>Your info</h1>
<div>
	<table>
		<tr><td>Username: <%= @user.username %></td></tr>
		<tr><td>Email Address: <%= @user.email %></td></tr>
		<tr><td>Address: <%= @user.address %></td></tr>
		<tr><td>City: <%= @user.city %></td></tr>
		<tr><td>State: <%= @user.state %></td></tr>
		<tr><td>Zip: <%= @user.zip_code %></td></tr>
		<tr><td><%= link_to "Update Info", '/user/' + @user.username + '/edit' %></tr>
		<tr><td><%= link_to 'Close Account', user_path(@user),class: 'error', method: :delete, data: { confirm: 'Close account? All your funds will be forfeited.' } %></td></tr>
	</table>
	<br>
	<%= link_to 'Back', '/' %>
</div>