config/routes.rb
Rails.application.routes.draw do
  get 'welcome_index/index'

  resources :accounts
  resources :users
  
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  
  get '/user/:username' => 'users#show'
  get '/accessdenied' => 'welcome_index#access_denied'
  
  get '/user/:username/edit' => 'users#edit'
  post '/user/:username/edit' => 'users#update'
  
  get '/accounts/:id/transactions/new' => 'transactions#new'
  post '/accounts/:id/transactions/new' => 'transactions#create'
  
  get '/accounts/:id/transactions/:transaction_id' => 'transactions#show'
  get '/accounts/:id/transactions' => 'transactions#index'
  
  get 'accounts/transactions/transfer' => 'transactions#new_transfer'
  post 'accounts/transactions/transfer' => 'transactions#transfer'
  
  get '/productivity' => 'time_waster#index'
  
  get '/snake' => 'time_waster#snake'
  get '/snake_score' => 'time_waster#snake_score'
  post '/time_waster' => 'time_waster#store_score'
  
  get '/pong' => 'time_waster#launch_pong', as: '/pong/play'
  get '/pong/servers' => 'time_waster#pong_server_browser'
  get '/pong/game/:id' => 'time_waster#pong'
  get '/pong/game/:id/begin' => 'time_waster#begin_pong_game'
  get '/pong/update/get/:id' => 'time_waster#pong_response'
  get '/pong/status/:id' => 'time_waster#pong_status'
  post '/pong/update/:id' => 'time_waster#pong_update_pos'
  
  root 'welcome_index#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/welcome_index_controller.rb
class WelcomeIndexController < ApplicationController
	def index
	end

  	def access_denied
	end
end

app/helpers/welcome_index_helper.rb
module WelcomeIndexHelper
end

app/views/welcome_index/access_denied.html.erb
<br><div><h1 style="color: red;">You do not have access to view this page!</h1></div>

app/views/welcome_index/index.html.erb
<h1>Welcome to FCBanking!</h1>
<div>
	<% if current_user %>
		<h3>Welcome <%= current_user.username.capitalize %>!<h3>
		<br>
		<div><%= link_to 'View your accounts', accounts_path %></div>
		<div><%= link_to 'View your information', '/user/' + current_user.username %></div>
		<div><%= link_to 'Waste Time', '/productivity', method: :get%></div>
	<% else %>
		<h3>Please sign in to access your accounts.</h3>
	<% end %>
</div>