config/routes.rb
Rails.application.routes.draw do
  get 'welcome_index/index'

  resources :accounts
  resources :users
  
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  
  get '/user/:username' => 'users#show'
  get '/accessdenied' => 'welcome_index#access_denied'
  
  get '/user/:username/edit' => 'users#edit'
  post '/user/:username/edit' => 'users#update'
  
  get '/accounts/:id/transactions/new' => 'transactions#new'
  post '/accounts/:id/transactions/new' => 'transactions#create'
  
  get '/accounts/:id/transactions/:transaction_id' => 'transactions#show'
  get '/accounts/:id/transactions' => 'transactions#index'
  
  get 'accounts/transactions/transfer' => 'transactions#new_transfer'
  post 'accounts/transactions/transfer' => 'transactions#transfer'
  
  get '/productivity' => 'time_waster#index'
  
  get '/snake' => 'time_waster#snake'
  get '/snake_score' => 'time_waster#snake_score'
  post '/time_waster' => 'time_waster#store_score'
  
  get '/pong' => 'time_waster#launch_pong', as: '/pong/play'
  get '/pong/servers' => 'time_waster#pong_server_browser'
  get '/pong/game/:id' => 'time_waster#pong'
  get '/pong/game/:id/begin' => 'time_waster#begin_pong_game'
  get '/pong/update/get/:id' => 'time_waster#pong_response'
  get '/pong/status/:id' => 'time_waster#pong_status'
  post '/pong/update/:id' => 'time_waster#pong_update_pos'
  
  root 'welcome_index#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
	belongs_to :user
	
	has_many :transactions, :dependent => :destroy
	
	POSSIBLE_ACCOUNT_TYPES = ['Checking', 'Savings']
	
	validates :balance, presence: true, numericality: { greater_than_or_equal_to: 0 }
	validates :account_name, presence: true, length: { maximum: 50 }
	
	attr_accessor :you
	attr_accessor :amount
	attr_accessor :account_selection
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
	before_action :authorize

	def index
	end
	
	def show
		@account = Account.find(params[:id])
		
		if @account.warning_threshold == nil
			@account.update(warning_threshold: 0)
		end
		
		unless current_user.id == @account.user_id
			redirect_to '/accessdenied'
		end
	end

	def edit
		@account = Account.find(params[:id])
		
		unless @current_user.id == @account.user_id
			redirect_to '/accessdenied'
		end
	end
	
	def new
		@account = Account.new
	end
	
	def create
		@account = current_user.accounts.create(balance: params[:account][:balance], account_type: params[:account][:account_type], account_name: params[:account][:account_name], warning_threshold: params[:account][:warning_threshold])
		
		if @account.save
			if @account.account_type == "Savings"
				@account.update(minimum_balance: 200)
				@account.update(interest_rate: 6)
				@account.update(transaction_counter: 3)
			else
				@account.update(minimum_balance: 0)
				@account.update(interest_rate: 0)
				@account.update(transaction_counter: 0)
			end
			
			@account.transactions.create(transaction_time: Time.now.asctime,transaction_amount: params[:account][:balance], target: 'Initial Deposit', operator: "+")
			
			
			redirect_to '/accounts'
		else
			render '/accounts/new'
		end
	end
	
	def update
		@account = Account.find(params[:id])
		
		if @account.update_attributes(account_update_params)
			redirect_to accounts_path
		else
			render 'edit'
		end
	end
	
	
	def destroy
		@account = Account.find(params[:id])
		
		if @account && current_user && @account.user_id == current_user.id
			@account.destroy
		end
		
		
		redirect_to '/accounts'
	end
	
	private
	
	def account_initial_params
		params.require(:account).permit(:account_type, :balance, :account_name, :warning_threshold)
	end
	
	def account_update_params
		params.require(:account).permit(:account_name, :warning_threshold)
	end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/edit.html.erb
<h1>Open a new account.</h1>
<div>
<%= form_for @account do |form| %>
	<% if @account.errors.any? %>
		<div class="error_messages">
			Form is invalid
			<p style="color: red;">
				<% for msg in @account.errors.full_messages %>
					<br><%= msg %>
				<% end %>
			</p>
		</div>
	<% end %>
	
	<div>
		<%= form.label :account_name, "Rename Your Account" %><br>
		<%= form.text_field :account_name %>
	</div>
	<div>
		Current Warning Threshold:<br>
		<%= number_to_currency(@account.warning_threshold, unit: "$") %>
	</div>
	<div>
		<%= form.label :warning_threshold, "Change Desired Warning Amount" %><br>
		$<%= form.number_field :warning_threshold, value: 0, step: 0.01 %>
	</div>
	<div><%= form.submit %></div>
<% end %>
</div>

app/views/accounts/index.html.erb
<h1>Welcome to the Account Management Page</h1>
<div>
	<% if current_user %>
		<div>
			<%= link_to 'Open an account', new_account_path %><br>
		</div>
		<% if current_user.accounts.length > 0 %>
			<% if current_user.accounts.length >= 2 %>
				<%= link_to 'Transfer Funds', '/accounts/transactions/transfer' %><br><BR>
			<% end %>
			<h3>Current Accounts</h3>
			<% for account in current_user.accounts do %>
				<table style="display: inline;">
					<tr>
						<% account_name = account.account_name %>
						<% account_funds = number_to_currency(account.balance, :unit => "$") %>
						<% final_link_name = account_name + ": " + account_funds %>
						
						<% if account.balance < account.warning_threshold %>
							<td style="color: red;">Warning: 
						<% else %>
							<td>
						<% end %>
		
						<%= link_to final_link_name, account_path(account.id) %></td>
					</tr>
				</table>
			<% end %>
		<% else %>
			<h3>You currently have no open accounts.</h3>
		<% end %>
	<% else %>
		<% redirect_to '/login' %>
	<% end %>
</div>

app/views/accounts/new.html.erb
<h1>Open a new account.</h1>
<div>
<%= form_for @account do |form| %>
	<% if @account.errors.any? %>
		<div class="error_messages">
			Form is invalid
			<p style="color: red;">
				<% for msg in @account.errors.full_messages %>
					<br><%= msg %>
				<% end %>
			</p>
		</div>
	<% end %>
	
	<div>
		<%= form.label :account_name, "Name Your Account" %><br>
		<%= form.text_field :account_name %>
	</div>
	<div>
		<%= form.label :account_type, "Account Type" %><br>
		<%= form.collection_select :account_type, Account::POSSIBLE_ACCOUNT_TYPES, :to_s, :to_s %>
	</div>
	<div>
		<%= form.label :balance, "Initial Account Balance" %><br>
		$<%= form.number_field :balance, value: 0, step: 0.01 %>
	</div>
		<div>
		<%= form.label :warning_threshold, "Desired Warning Amount" %><br>
		$<%= form.number_field :warning_threshold, value: 0, step: 0.01 %>
	</div>
	<div><%= form.submit %></div>
<% end %>
</div>

app/views/accounts/show.html.erb
<h1>Your info</h1>
<div>
	<% if @account.account_type == "Savings" && @account.balance < @account.minimum_balance %>
		<h3 style="color: red;">Warning: You've fallen below the minimum balance required for this Savings Account!</h3>
	<% end %>

	<% if @account.balance < @account.warning_threshold %>
		<h3 style="color: red;">Warning: You've fallen below your desired threshold!</h3>
	<% end %>
	
	<h3><%= @account.account_name %></h3>
	
	<table>
		<tr><td>Account Type: <%= @account.account_type %></td></tr>
		<tr><td>Account Balance: <%= number_to_currency(@account.balance, :unit => "$") %></td></tr>
		<% if @account.account_type == "Savings" %>
			<tr><td>Minimum Required Balance: <%= number_to_currency(@account.minimum_balance, :unity => "$") %></td></tr>
			<tr><td>Account Interest Rate: <%= number_with_precision(@account.interest_rate, precision: 0) %>%</td></tr>
			<tr><td>Remaining Transactions This Month: <%= number_with_precision(@account.transaction_counter, precision: 0) %></td></tr>
		<% end %>
		<tr><td><%= link_to "View Transactions", '/accounts/' + @account.id.to_s + '/transactions' %></tr>
		<tr><td><%= link_to "Make a Transaction", '/accounts/' + @account.id.to_s + '/transactions/new' %></tr>
		<tr><td><%= link_to "Transfer Funds", '/accounts/transactions/transfer' %></tr>
		<tr><td><%= link_to "Edit Your Account", '/accounts/' + @account.id.to_s + '/edit' %></tr>
		<tr><td><%= link_to 'Close Account', account_path(@account), class: 'error', method: :delete, data: { confirm: 'Close account? All your funds will be forfeited.' } %></td></tr>
	</table>
	<br>
	<%= link_to 'Back to Accounts', accounts_path %>
</div>